"""remove strava add gpx import

Revision ID: c62672f67488
Revises: 62b3144af731
Create Date: 2026-06-16 10:15:31.841546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c62672f67488'
down_revision: Union[str, None] = '62b3144af731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
